<?php

// BEGIN iThemes Security - Ne modifiez pas ou ne supprimez pas cette ligne
// iThemes Security Config Details: 2
define( 'FORCE_SSL_ADMIN', true ); // Rediriger toutes les requêtes de pages de HTTP vers HTTPS - Sécurité > Réglages > Forcer le SSL
define( 'DISALLOW_FILE_EDIT', true ); // Désactivez l’éditeur de code - Solid Security > Réglages > Ajustements WordPress > Éditeur de code
// END iThemes Security - Ne modifiez pas ou ne supprimez pas cette ligne

define( 'ITSEC_ENCRYPTION_KEY', 'LVtWdzMzYk44Kj1uVl55LFA/JSwyT1BSbj9wXigjKDxDW1ZzdztTcks+bjRbUVcjbVZ6WGI/SVBwZ2BRN0lgRg==' );

define( 'WP_CACHE', true ); // Added by WP Rocket

/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */
require_once dirname(__DIR__) . '/vendor/autoload.php';
require_once dirname(__DIR__) . '/config/application.php';
require_once ABSPATH . 'wp-settings.php';
